---
- name: bootstrap personal servers
  hosts: all
#  become: true
#  become_user: root
  roles:
    - common
    - chrony
    - users
#  - auditd
#  - etc_issue
    - sudoers
    - fail2ban
    - rsyslog
#  - iptables
#  - ntpd
#  - sysctl
#  - mail # This section should always be last
