---
- name: bootstrap personal servers
  hosts: all
#  become: true
#  become_user: root
  roles:
    - common
    - chrony
    - users
    - sudoers
    - fail2ban
    - rsyslog
    - sshd
#  - mail # This section should always be last
