---

- name: ensure kpnet group exist
  group: name=kpnet gid=9000 state=present

- name: ensure jlim user exists
  user: name=jlim comment="Justin Lim" uid=9000 group=kpnet groups=wheel password="$6$riT5yR/xBlzdb2hZ$1KQFXaEz9MUQWhsa4BugBGsn97KV.V9Yt11GxcH0AKwqy6gW4vK93lIXDLUcqUWrK9nlKSR/v/qNFc0faYEi/1"

- name: ensure jlim keys exist
  authorized_key: user=jlim key="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCmC2ohBmGoy/Te8cKFMavTYAVBNVcAPlM93AsWqqI6hVSSjYG+M7iM8onEk8WjA/xZ7sQlD9Z+bLxB3oqenMU076QxdCPuAY07t2TAM/I4mG/y78fBqZKHthJQ0+9bXcTbizTsysm+QUpPRH76Qr8z1sHcdRz85LBhXNJcakzHyKfJxFb162eW+Anzb5nsxWWNBrNH/P8siwHXPaS1wp1pqBfjak+ExmrOOmJltKcudVZ+dkGyYOAoN0uREsMSRztlL4sSouUV8VEZKlMZYnzrCUezUpY6hIlX/6wn0hj6LNzj2xDKNqJsHxKOW33M0Z4YIfoIsiD4+50foQmhTLap jlim@batz.home.local"

- name: create id_rsa.pub as 0644
  copy:
    dest: /home/jlim/.ssh/id_rsa.pub
    backup: yes
    group: kpnet
    owner: jlim
    mode: 0644
    content: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCfPQtRLrG2CXOvbqfcnZupFJ4p7udmeTDex8J6bg/dm5ekfRweI29ts12hw6nyijIqv9ttBphRzSmCED8Pus4hTNcLtODklFyuqWrU6xhWUEi6cweDo12TIBCj/WvegoAE1H6YfLQb76adACyJsz8+bRU/3yL1Z2QDaMXE3aZ95rMkCMMCpGY2qzCO+Bvk1TYJgj24YSDDxCmgeM7Q5cMeWK/JRWFPZOGAdpXQno4EHTPoqNl4dE7hw19VJguFjezd/iZkWxLVjxTNDb1NN6JKL+iqlq+zmbPVLuQMcnlDiaNBUDRFe3ATe76S/nfWzK3jgxThtPr7FG0WU9PVXXpl jlim@batz.home.local"
    
- name: create id_rsa for the key as 0600
  copy:
    dest: /home/jlim/.ssh/id_rsa
    backup: yes
    group: kpnet
    owner: jlim
    mode: 0600
    content: "-----BEGIN RSA PRIVATE KEY-----
MIIEowIBAAKCAQEAnz0LUS6xtglzr26n3J2bqRSeKe7nZnkw3sfCem4P3ZuXpH0c
HiNvbbNdocOp8ooyKr/bbQaYUc0pghA/D7rOIUzXC7Tg5JRcrqlq1OsYVlBIunMH
g6NdkyAQo/1r3oKABNR+mHy0G++mnQAsibM/Pm0VP98i9WdkA2jFxN2mfeazJAjD
AqRmNqswjvgb5NU2CYI9uGEgw8QpoHjO0OXDHlivyUVhT2ThgHaV0J6OBB0z6KjZ
eHRO4cNfVSYLhY3s3f4mZFsS1Y8UzQ29TTeiSi/oqpavs5mz1S7kDHJ5Q4mjQVA0
RXtwE3u+kv531syt44MU4bT6+xRtFlPT1V16ZQIDAQABAoIBAESpis63prNKwhJc
UY9kenFezZBhTnA2Q6dcVXR7LuYsqCeqNsycFPklhXMyLn7Brj4WumP5mwZyw7os
jTSYJTfgrT2EAhEuFATQUpt6v+S/+4xB+3R8peXBxssfhDrO5KqwgeH4q6T8IkjC
gXHi05t0Z9xBuA4/RbXeoKBxvs+8U1PfnkRIX5/Pp/fTcYLIqnn2eQCU1S1csKgB
LPVwDbLvdZkbcapNnX4qdBBHE+4oMfqCIIh7L4fAL3Hv5Kcxg097DUfD+vM3Qavh
MeDyaAAds9V1WuBiXgXmFehbyyV6s4mUIYusb82SmqbijbioroaLOXYoqLKsKsVd
9ubyd0ECgYEAy6HpNQxLVZr0Bov6cfuuu8fpD+70tWiKo11Kn3txVR+wnZqLmn04
/pzQ2zrl6awAnYHY7NhPeGG3pMgj2lYk/cBwOMxtwvK5+5+uC9Rmtv6q5MZK0VZ+
dy+rwzeiuATwKOACKxpzJAQuYtuBjr5U30phl0lqwJBlY93p2X258/UCgYEAyDB3
IuKVlIrx0tKqhpG84f6ymVE/XJ2QvrQA49IruGyRlOP88U0cAfIY2WygyZ6+eMEF
eNhilZeznAVKrWlLuRr6dTNAVPUVpSpppr6mWd/NDaWdcUI8KbOdvtqA2txv2fyk
v34WBr1gnaTn63LyPRJFVlan7WcUVufx2jFJ1rECgYAIXhXcJS4vTVe7sSLQbjwm
4TcVfYc2sR4JSnsXhJYKnmu+fixAY+bkp4L5jzkFWhkIX96PFPBnDPTj44l9nk6U
0sSJwPS9rwWvbkdTmx3BZUOWdQN8CKbXtPDE69NW5nUL6PCN3t9eWoGhdE2llPKd
3kuWUOD/Gq/f462JT15FxQKBgQC6VKIPTmd7w3giiwM+DhiJIdCK9BzNz7sSReku
JEmddzBqLWsaDnOrO/P1LC7ce20+aCr3uDDKnFEJP8OqdP+OY5YL0JBog1aKTVfZ
ZEriDHWH5kcNTGFDT3PcWPTmwZc6hvWxZ2KJE2wCT6Oue2cNgRwYqL/VMMS1v15V
gNsBgQKBgBxG4UDG36VA9819VQliN6xqUU0v03Cl2ipu54Pe6jzTi7V8mQPQjaDc
a5dHy78gMA57G4vH5AlQl5FnKA4mH+KFPHFbbEne9YL4H+LTnCiLVAfDIuAo6deD
8BvsUl9i49oIujSd48AkiBzbZdLltpGk3FnDACOQr+LTy+PJQdb5
-----END RSA PRIVATE KEY-----"

