---

- name: ensure kpnet group exist
  group: name=kpnet gid=9000 state=present

- name: ensure jlim user exists
  user: name=jlim comment="Justin Lim" uid=9000 group=kpnet groups=wheel password="$6$riT5yR/xBlzdb2hZ$1KQFXaEz9MUQWhsa4BugBGsn97KV.V9Yt11GxcH0AKwqy6gW4vK93lIXDLUcqUWrK9nlKSR/v/qNFc0faYEi/1"

- name: ensure jlim keys exist
  authorized_key: user=jlim key="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCmC2ohBmGoy/Te8cKFMavTYAVBNVcAPlM93AsWqqI6hVSSjYG+M7iM8onEk8WjA/xZ7sQlD9Z+bLxB3oqenMU076QxdCPuAY07t2TAM/I4mG/y78fBqZKHthJQ0+9bXcTbizTsysm+QUpPRH76Qr8z1sHcdRz85LBhXNJcakzHyKfJxFb162eW+Anzb5nsxWWNBrNH/P8siwHXPaS1wp1pqBfjak+ExmrOOmJltKcudVZ+dkGyYOAoN0uREsMSRztlL4sSouUV8VEZKlMZYnzrCUezUpY6hIlX/6wn0hj6LNzj2xDKNqJsHxKOW33M0Z4YIfoIsiD4+50foQmhTLap jlim@batz.home.local"

- name: create id_rsa.pub as 0644
  copy:
    dest: /home/jlim/.ssh/id_rsa.pub
    backup: yes
    group: kpnet
    owner: jlim
    mode: 0644
    content: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCdk/XvOXljzJKviLtlDVPQ9Y+e2S/tvDS8xMAGY2m7JLfIxUYse2FYcrWcVdFtRNlOFJ490arxsLc8b5ZN1lB+yOMHJerA9z5hpiVKgMJHw9aFgdvYxIagDPW5mAeTAXC/uPTL0X26WIZJkl6IMYywAUp68zUeawT+irBopUbiGWGyiwHRfbQ9apIV9rF8xJLYOiXu9Ownvl9WNR2ejnoRWx+5Pnr8uBcUhc5AvKZBX1xqrwqj+A5biM/zlrzFNWv3HtbaswkClGpUVcqw7PrbtrJdu9Ohbw5yvjXgPi+soR/uUCLcz0H/4K+JpqdfxWsgxi4Uv9ouqjHMuUkWTXsft8WvnBDxbes1IRnL9QCN/EgiEP3y5Q7SQe2FoQ5UnrMTw6ThopOdzKVAf/XfsHtqX3dVgM+8f8L6lX8gMYLHNJdBctwYKCCKcqqTjqrpmOmMBlcHTFBrjBLJ2Ukj79ln13csdo+D/2QrsKg7LWI0xrZh2iuzv8f5JXF4djYK3TU0hwleyYcblfDiCd4Srqb8oJfxNryNyfZD/nwRz6j9wlHvRsYMfYUbIYcbb5Xo+zW8nBQh88n9knppfnP3Wzyv+MjyPNTTM6mdUgob/VjRkkwxbkRGalmCJusdkgDkROub7gnt0GE/urab0GWCmy3QSanAun0d842uA8IIX3RotQ== jlim@batz.home.local"

- name: create id_rsa for the key as 0600
  copy:
    dest: /home/jlim/.ssh/id_rsa
    backup: yes
    group: kpnet
    owner: jlim
    mode: 0600
    content: "-----BEGIN RSA PRIVATE KEY-----
MIIJJwIBAAKCAgEAnZP17zl5Y8ySr4i7ZQ1T0PWPntkv7bw0vMTABmNpuyS3yMVG
LHthWHK1nFXRbUTZThSePdGq8bC3PG+WTdZQfsjjByXqwPc+YaYlSoDCR8PWhYHb
2MSGoAz1uZgHkwFwv7j0y9F9uliGSZJeiDGMsAFKevM1HmsE/oqwaKVG4hlhsosB
0X20PWqSFfaxfMSS2Dol7vTsJ75fVjUdno56EVsfuT56/LgXFIXOQLymQV9caq8K
o/gOW4jP85a8xTVr9x7W2rMJApRqVFXKsOz627ayXbvToW8Ocr414D4vrKEf7lAi
3M9B/+CviaanX8VrIMYuFL/aLqoxzLlJFk17H7fFr5wQ8W3rNSEZy/UAjfxIIhD9
8uUO0kHthaEOVJ6zE8Ok4aKTncylQH/137B7al93VYDPvH/C+pV/IDGCxzSXQXLc
GCgginKqk46q6ZjpjAZXB0xQa4wSydlJI+/ZZ9d3LHaPg/9kK7CoOy1iNMa2Ydor
s7/H+SVxeHY2Ct01NIcJXsmHG5Xw4gneEq6m/KCX8Ta8jcn2Q/58Ec+o/cJR70bG
DH2FGyGHG2+V6Ps1vJwUIfPJ/ZJ6aX5z91s8r/jI8jzU0zOpnVIKG/1Y0ZJMMW5E
RmpZgibrHZIA5ETrm+4J7dBhP7q2m9Blgpst0EmpwLp9HfONrgPCCF90aLUCAwEA
AQKCAgAD6DxL3zf0Uok8kv5ahhcS8lPKU4ZNtcH1AEfmoKZpfoKUFtgjmDeUsttv
8ezMcc2VkwtNaxp6/a+9buLiMTMzwZVngvgsKrVARJdeHo0yrFdwXgTufgj8hPW+
0Vc2vO1nw5VGTH56lWFXB6sSY3AimRWYsNkbVPn9ucCgB6EXUBvNCodUA3Lppu/S
XZiPCGy/sclpAGeuoJjKkWyXlt7N+V1zAWqZQ5NG7f5sOoFA07V967Mu16K7gEvv
tUge97EiooAfUhsiFj4As1PgSS/7LK+FhXe84/0OuUqqscAK3r/k79W9deIkDxUr
K5ew1ztNx7wyxYMKbyvm8J0wUWGBIN5nx+J0JJFUBXXBVqHXz8QJqG8+Mzk9L/0x
+6yb7ziV7gXo1S4O26xVfbuqCCdhE9TCEFZWhIj55w6V4CQzGIVXVGaMDIXYwC5n
cboQaZ+exYIA2OUKlYCuEiv+2BLuoAbJY23/dM4cWVtvKwwhJ/L0hyLOUY1vw91T
58+fBV46kpKtkkfB2HwGuxTy2d+QQPgRTdZXnGn01ERkGXvnTgkGLofp6hAu1CD+
Jr8I74wLfIFNtQW4TPy45MhUKQ8GXPS6tCpGWvgRfPZ1xlfYfftnejb7d0CuVMdt
toKGP7MZ1stHAgWmcYvfoSIIIXBCwfEUyWsgmghx9/usVrb7wQKCAQEAyxue68wJ
ewhXfibhRkDKm29OKFT4hNULpj1PJRNyNQkDH2Q6xznzPTx9wfc53pyjGtax9sHA
X5XWT3vEgfpS2kBNPGDsIug4pO3OMrMsnizl9AB3B0RJ5MRTxSM7fLhlHw8TSdrA
Y2+M+HCO1GSzVVJEoDuceRF1/k8lbTjsTvrEkeZC+W0FlLZAo0/cCOI2WLgLOVBn
fv9Zzmhb5S19oixn6EXcgPnVKYzRTV4IUwpcFkCd27fhfOUTjmCpj+uUzIvPtsYC
HwHz88JkgvMjazIOmrqp7Et/7XUZuZiXk/o1XozrQSeRFVqzDm6pr0KX1nIFaE6H
XYoelevNn9nacQKCAQEAxp0LcbCAIKfahOTtdQ+5CtrPG7fYHdUzlr6Nn6XgE5D+
HRwgJbnCO7nd/FsAlzN/ZbyKKRrtBaHPCjqqLs/wiYhJe1hI/xeqflBJMsUlegXX
hL8c97arkk/yPgr3Z6n1fl4bqUIYFLK+oE5GqNC7j++ePGfn9U3bU7PtFftBX466
0c8eLrsSBzxUWOZyEU1XIdtxvdUoOMIZ4wGJMdjL6UV5k2sqKUUHOB+9VdyOLDCS
D4xGcfU6sWKgiBCifSYIHRm+B995IsRC9qDEbWGcOHKZq5ue+dtYzFMfG/Q7U6AG
otji2NmCqWeyZ+fW9P6RHMEl5VYgkH4f+1zfyaKshQKCAQA++9K9ZmluOLkBCseD
BKaPquV+xlLGxlY1d/+qDKy225OXUXqUu1i9nZuV4beVW9eMhBVt4sloGsv5m/Tl
JZ45xgTte1TewkqGgqQVvtBQQLYSg25l13xer68WjAVveLMK/Z7KoUZVz4rUo/r2
zD98buWPFs1AEfUYJq0BgMxu9X6ti80rEe7QHfBPdH1UV+noezIn1NIzZLYRtvUA
TaoO91xFgByP9mlu2Bczubw1HBpQYDtTnmMTWupElZ8fXTuobpa8JA0WVoGzDo4i
uYk7PaufudDl0Mfb+BtBHZurrMSODH8Lllx8VcL+77w4+Bqjynn4zZlWnXU8ooIC
VwlRAoIBAGfgEvAvA5QQtfTzVk33HyxSLCevC1TvAMBCgQeSVZNmLcFDyHxynudl
2nf1kGWEBYlMBmZhMr3TVtlevUsmbgNASE4+ak8gLYdKrj3jZipfi8xdt+TGoQ0w
yt0wFx0cgszIo2burnGE2rY0ujfok3BAPl4Rafud8KviWok4k4RKveKllH+UT2WB
ZAvq2pW6AWwvvVkvdo3Y1nkngH2ViXBDacZ0MeTLuW7dCsUxSRpLfNis4NsRCtVj
Y9pF+PXDQlMV95Fei5hnVS5v/svGVVIgfcaG6ap70gFrJ8YTAkRGWbIqBNqtR+0Z
0vENDBuuWG7VheBgHz/y9v8cH97xOZECggEAemv5kHSEx3bUbx4UnLAD/sEMO/Zi
Dwl4baCIWQ5ixc4Jce50SdmHzh7vq0rw4fa7es55VGRNp1XgCNeE1w9j+S1mnkgD
IoPAX/7LNdyadW3i9cQZix11u2AM31w224vRvo0d+H2jB5dAzldomMsJcK95HaoV
zZyfg1vTD+IbDDcVOiknHLnt919U94I2weBOXCaY8xMrwDT8W3qTYQYwLca29n4x
X1jKgqZmsXLOdfh5nCDVQP1cYcYGDhyH1MD4XplWOZ9cpbUqdSR/bAe35WP8BKlM
PmPMjoT0p2tT+Qp20fq3DE4wRoyyEPzo3DZb8pfXtUD1NOi4py0Xqoif1g==
-----END RSA PRIVATE KEY-----"

