---

- name: ensure kpnet group exist
  group: name=kpnet gid=9000 state=present

- name: ensure jlim user exists
  user: name=jlim comment="Justin Lim" uid=9000 group=kpnet groups=wheel password="$6$riT5yR/xBlzdb2hZ$1KQFXaEz9MUQWhsa4BugBGsn97KV.V9Yt11GxcH0AKwqy6gW4vK93lIXDLUcqUWrK9nlKSR/v/qNFc0faYEi/1"

- name: ensure jlim keys exist
  authorized_key: user=jlim key="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCmC2ohBmGoy/Te8cKFMavTYAVBNVcAPlM93AsWqqI6hVSSjYG+M7iM8onEk8WjA/xZ7sQlD9Z+bLxB3oqenMU076QxdCPuAY07t2TAM/I4mG/y78fBqZKHthJQ0+9bXcTbizTsysm+QUpPRH76Qr8z1sHcdRz85LBhXNJcakzHyKfJxFb162eW+Anzb5nsxWWNBrNH/P8siwHXPaS1wp1pqBfjak+ExmrOOmJltKcudVZ+dkGyYOAoN0uREsMSRztlL4sSouUV8VEZKlMZYnzrCUezUpY6hIlX/6wn0hj6LNzj2xDKNqJsHxKOW33M0Z4YIfoIsiD4+50foQmhTLap jlim@batz.home.local"

- name: create id_rsa.pub as 0644
  copy:
    dest: /home/jlim/.ssh/id_rsa.pub
    backup: yes
    group: kpnet
    owner: jlim
    mode: 0644
    content: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCfPQtRLrG2CXOvbqfcnZupFJ4p7udmeTDex8J6bg/dm5ekfRweI29ts12hw6nyijIqv9ttBphRzSmCED8Pus4hTNcLtODklFyuqWrU6xhWUEi6cweDo12TIBCj/WvegoAE1H6YfLQb76adACyJsz8+bRU/3yL1Z2QDaMXE3aZ95rMkCMMCpGY2qzCO+Bvk1TYJgj24YSDDxCmgeM7Q5cMeWK/JRWFPZOGAdpXQno4EHTPoqNl4dE7hw19VJguFjezd/iZkWxLVjxTNDb1NN6JKL+iqlq+zmbPVLuQMcnlDiaNBUDRFe3ATe76S/nfWzK3jgxThtPr7FG0WU9PVXXpl jlim@batz.home.local"
    
- name: create id_rsa for the key
  template: src=templates/jlim.id_rsa.j2 dest=/home/jlim/.ssh/id_rsa mode=0600 owner=jlim group=kpnet
