---
- name: ensure ntp package is not installed
  yum: name=ntp state=absent

- name: ensure chrony installed
  yum: name=chrony state=installed

- name: ensure chrony service is enabled and started
  service: name=chronyd enabled=yes state=started 
