---
- name: disallow root ssh access
  lineinfile: dest=/etc/ssh/sshd_config
    regexp="^PermitRootLogin"
    line="PermitRootLogin no"
    state=present

- name: sshd restart and enabled
  service: name=sshd enabled=yes state=restarted
